### ISSUE TITLE
Legal Stuff

### ISSUE THREAD

**Issue by IsaiahKelly** [UnityTechnologies/MinecraftECS#2]
It might be a good idea to add a license to the project. Especially if you start accepting community contributions. Something like the [Unlicense](https://choosealicense.com/licenses/unlicense/) would work well I think.

"Minecraft" is a register trademark owned by Microsoft. So it might be a good idea to rename the project to something more generic like "VoxelSandboxECS" just to be safe.

Textures may also be a copyright issue if they are from the actual game, but these could be easily replaced with some free open source textures by Kenny, which I'd be happy to do for you.

**Comment by DadaTheArtist** [comment]
Thanks and will do!
