### ISSUE TITLE
Can't run the project in any unity version

### ISSUE THREAD

**Issue by FlameskyDexive** [UnityTechnologies/MinecraftECS#3]
cause entities version has update to several version, will you update the project to unity 2019.3 or newer version?  i can't running this project in unity 2018.4, and update the packages still can't run success.

**Comment by bcmRayCrazy-coder** [comment]
you can rewrite all

**Comment by DadaTheArtist** [comment]
I've upgraded it to Entities 1.0.0-exp.8 now
